[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10000
via_ir = true
isolate = true          # CRITICAL: required for CoFHE permission checks
gas_reports = ["OccultMarket"]

[profile.ci]
fuzz = { runs = 10000 }

[rpc_endpoints]
fhenix_testnet = "${FHENIX_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
